### ISSUE TITLE
Unable to read file ...StateTL_llave.mat No such file or directory

### ISSUE THREAD

**Issue by LyonsR** [OpenCDSS/ArkDSS-Colors-of-Water#10]
When I try to run the latest code I receive the following error at line 72:

Error using load
Unable to read file 'O:\Projects\ArkDSS\modeling\models\Matlab20211013\StateTL_llave.mat'. No such file or directory.

Error in StateTL (line 72)
load([basedir 'StateTL_llave.mat']);

If I comment out that code I get the following error:

Unrecognized function or variable 'prevutmx'.

Error in StateTL (line 648)
                utmx=prevutmx;  %hopefully the first two are missing

It seems that prevutmx does not exist before this line and the same issue exists for the subsequent three lines containing the variables prevutmy, prevlat, and prevlon

**Comment by kelleythompson** [comment]
Closing issue with note that required files must also be downloaded from the CoW shared drive in order to run StateTL.m
