### ISSUE TITLE
Uploaded python script

### ISSUE THREAD

**Issue by LyonsR** [OpenCDSS/ArkDSS-Colors-of-Water#17]
I have uploaded the Python script and updated the README.md with basic instructions on setting up an environment and running the script. This initial Python script runs multiple instances of the Matlab code and writes the results into individual folders in the tests directory. The results will be identical in all folders. Kelley, I would like you to run the script and report back.

**Comment by kelleythompson** [comment]
Yes things worked successfully with this code.  I was able to successfully
create a new python environment from an Anaconda command prompt using
the environment.yml file, and then to run the python code.  The code
successfully completed the 12 instances of the calibration run in about 4
minutes on my DWR local desktop.

Just for myself, the commands I used (as indicated by readme) were:
$ conda env create -n calibrationenv -f
C:\Projects\Ark\ColorsofWater\ArkDSS-Colors-of-Water\environment.yml
$ conda activate calibrationenv
$ cd python
$ python run_arkdss_calibration.py

My only personal headache is the version of spyder that came with the
newest version of Anaconda won't launch for me (throws errors)  - but maybe
there will be updates before I really need to look closely at the python.

Thanks,
Kelley

*Kelley L. Thompson, P.E.*
*Senior Lead Modeler - Modeling and DSS / Water Information Team*

P 303.866.3581 ext 8261 |  C 719.480.3423
1313 Sherman St., Suite 818, Denver, CO  80203
***@***.***  |  www.water.state.co.us
